### ISSUE TITLE
add encryption options

### ISSUE THREAD

**Issue by wanderer** [ethereumjs/helpeth#10]
it would be fun to add an option to encrypt and decrypt some text given a public key (possible derived from a tx) and a private key

**Comment by axic** [comment]
Do you mean using ECIES or custom scheme based on ECDH?

**Comment by wanderer** [comment]
I would just use ECDH, then encrypt with AES.

**Comment by artyomLisovskij** [comment]
I think Keccak as option and other crypto may be useful too.
