### ISSUE TITLE
how to run pyethrecover on windows

### ISSUE THREAD

**Issue by alyfree** [ethereumjs/helpeth#14]
how to run pyethrecover on windows

**Comment by alyfree** [comment]
how to run pyethrecover on windows

**Comment by alyfree** [comment]
how to run pyethrecover on windows

**Comment by alyfree** [comment]
how to run pyethrecover on windows

**Comment by alyfree** [comment]
how to run pyethrecover on windows

**Comment by alyfree** [comment]
how to run pyethrecover on windows

**Comment by fanatid** [comment]
wrong repo
