### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by marek22k** [ethereumjs/helpeth#26]
Input: `$ helpeth addressDetails 0x0000000000000000000000000000000055000000`
or generic `$ helpeth addressDetails [ADDRESS]`
Output:
```
Address: 0x0000000000000000000000000000000055000000
Address (checksum): 0x0000000000000000000000000000000055000000
ICAP: XE11 0000 0000 0000 000N L1HJ 4
Segmentation fault (core dumped)
```
OS: `Debian 11 in Linux Container on Chrome OS (Chromebook)`
Installed via: `npm`

The expected output appears, but also the message "Segmentation fault (core dumped)". I installed it in the "default container" on my Chromebook.

**Comment by acolytec3** [comment]
This is an unsupported repo at this point.  If you need a CLI tool for interacting with the blockchain (with likely some overlapping functionality), you could try [eth-cli](https://github.com/protofire/eth-cli).
